### ISSUE TITLE
git commands

### ISSUE THREAD

**Issue by christensonb** [SeabornGames/Games#2]
Create file call git_commands under seaborn.

The setup should create command to run the routines in the git_commands.

Create the following git commands for doing the following:

seaborn_status: goes through all the sister repos and prints a git status
seaborn_commit: goes through all the sister repos and if there is something to commit, commits it with the message from sys.argv[1]

seaborn_push: goes through all the sister repos and if the branch is different from the origin pushes the current branch to origin <current branch>

seaborn_pull: goes through all the sister repos and does a "git pull origin <current branch>"

**Comment by MichaelChristenson** [comment]
Pushed to 1_test_runner in games repository
